pipeline {
    agent {label 'built-in'}

    environment {
        REPO_URL = 'https://github.com/rushibhosale/priv_repo.git'
    }

    stages {
        stage("Cleanup Old Containers") {
            steps {
                echo "Removing previous containers..."
                sh 'docker rm -f container-branch1 container-branch2 container-branch3 || true'
            }
        }

        stage('Deploy Branch 1 (Port 80)') {
            steps {
                dir('branch1_dir') {
                    echo "Checking out 2026Q1 branch"
                    git branch: '2026Q1',
                        url: "${REPO_URL}",
                        credentialsId: 'github-token'

                    sh '''
                    # 1. Fix permissions on the Jenkins host before mounting
                    chmod 644 index.html
                    
                    # 2. Use -v to bind mount the file from the current directory ($PWD) directly into the container
                    docker run -d --name container-branch1 -p 80:80 -v "$PWD/index.html":/usr/local/apache2/htdocs/index.html httpd
                    '''
                }
            }
        }

        stage('Deploy Branch 2 (port 90)') {
            steps {
                dir('branch2_dir') {
                    git branch: '2026Q2',
                        url: "${REPO_URL}",
                        credentialsId: 'github-token'

                    sh '''
                    chmod 644 index.html
                    docker run -d --name container-branch2 -p 90:80 -v "$PWD/index.html":/usr/local/apache2/htdocs/index.html httpd
                    '''
                }
            }
        }

        stage('Deploy Branch 3 (port 8081)') {
            steps {
                dir('branch3_dir') {
                    git branch: '2026Q3',
                        url: "${REPO_URL}",
                        credentialsId: 'github-token'

                    sh '''
                    chmod 644 index.html
                    docker run -d --name container-branch3 -p 8081:80 -v "$PWD/index.html":/usr/local/apache2/htdocs/index.html httpd
                    '''
                }
            }
        }
    }
}